### ISSUE TITLE
Consent string decoded but 'isVendorAllowed' fails with VendorConsentParseException

### ISSUE THREAD

**Issue by sergshyn** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#40]
Hi,
I've found that some consent strings (for example `BAAAAAAOXS4XyAcABBENBf4AAAAgmAIAAyABiAEAAFAA0AC2AEUAJgAkAA`) are decoded correctly but calling of method 'isVendorAllowed'  will lead to following exception:
```java
Exception in thread "main" com.iab.gdpr.exception.VendorConsentParseException: Start VendorId must not be greater than End VendorId and End VendorId must not be greater than Max Vendor Id
	at com.iab.gdpr.consent.implementation.v1.ByteBufferBackedVendorConsent.isVendorPresentInRange(ByteBufferBackedVendorConsent.java:159)
	at com.iab.gdpr.consent.implementation.v1.ByteBufferBackedVendorConsent.isVendorAllowed(ByteBufferBackedVendorConsent.java:119)
```

Code for reproducing:
```java
VendorConsent vendorConsent = VendorConsentDecoder.fromBase64String("BAAAAAAOXS4XyAcABBENBf4AAAAgmAIAAyABiAEAAFAA0AC2AEUAJgAkAA");
vendorConsent.isVendorAllowed(1); // VendorConsentParseException
```

while I was able to do the same using js lib:
```js
const consentDataTest = new  ConsentString('BAAAAAAOXS4XyAcABBENBf4AAAAgmAIAAyABiAEAAFAA0AC2AEUAJgAkAA');
console.log ("consentDataTest: ", consentDataTest);
console.log("vendor 1 test: ", consentDataTest.isVendorAllowed(1));
console.log("purpose 1 test: ", consentDataTest.isPurposeAllowed(1));
```

got 
```js
  consentDataTest:  ConsentString {
  created: 1970-01-01T00:00:00.000Z,
  lastUpdated: 2018-11-15T22:31:39.400Z,
  version: 1,
  vendorList: null,
  vendorListVersion: 95,
  cmpId: 28,
  cmpVersion: 1,
  consentScreen: 1,
  consentLanguage: 'en',
  allowedPurposeIds: [ 1, 2, 3 ],
  allowedVendorIds: [ 24, 25, 52, 69, 76, 91, 144 ],
  maxVendorId: 521 }
 vendor 1 test:  false
 purpose 1 test:  true
```

Also there is no problem with decoding using https://www.decodeconsentstring.com/v1.0/?consent-string=BAAAAAAOXS4XyAcABBENBf4AAAAgmAIAAyABiAEAAFAA0AC2AEUAJgAkAA

Could you please help?

Regards, Sergey

**Comment by lanusau** [comment]
This is an incorrectly encoded consent string. It uses range encoding with 8 entries, 7 entries are single vendor IDs but 3rd entry is has range of vendor IDs with starting vendor ID = 32 and ending vendor ID = 10, which is obviously not correct. The Javascript library probably just quietly ignores that entry, as you can see from the output, because it only prints 7 allowed single vendor IDs, not printing the range entry. 

I think throwing exception is the correct behavior. You should catch the exception and assume no consent. Ignoring incorrectly encoded entries may lead us to assume consent where user did not intend one.

**Comment by sergshyn** [comment]
Thank you for the quick response. 
So, let's consider such consent strings as incorrectly encoded.
